package entities;
// Generated May 20, 2017 8:58:53 PM by Hibernate Tools 4.3.1



/**
 * Major generated by hbm2java
 */
public class Major  implements java.io.Serializable {


     private Integer majorId;
     private String majorName;
     private String majorYear;

    public Major() {
    }

    public Major(String majorName, String majorYear) {
       this.majorName = majorName;
       this.majorYear = majorYear;
    }
   
    public Integer getMajorId() {
        return this.majorId;
    }
    
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }
    public String getMajorName() {
        return this.majorName;
    }
    
    public void setMajorName(String majorName) {
        this.majorName = majorName;
    }
    public String getMajorYear() {
        return this.majorYear;
    }
    
    public void setMajorYear(String majorYear) {
        this.majorYear = majorYear;
    }




}


