package entities;
// Generated May 20, 2017 8:58:53 PM by Hibernate Tools 4.3.1



/**
 * ReportAttendance generated by hbm2java
 */
public class ReportAttendance  implements java.io.Serializable {


     private Integer id;
     private String otherSpecify;
     private String studentId;
     private String subjectId;
     private String state;
     private String date;
     private String time;
     //new
     private int attend;
    private int absent;
    private int late;
    private int sl;
    private int pbl;

    public ReportAttendance() {
    }

    public ReportAttendance(String otherSpecify, String studentId, String subjectId, String state, String date, String time) {
       this.otherSpecify = otherSpecify;
       this.studentId = studentId;
       this.subjectId = subjectId;
       this.state = state;
       this.date = date;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getOtherSpecify() {
        return this.otherSpecify;
    }
    
    public void setOtherSpecify(String otherSpecify) {
        this.otherSpecify = otherSpecify;
    }
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }


    //
    public int getAttend() {
        return attend;
    }

    public void setAttend(int attend) {
        this.attend = attend;
    }

    public int getAbsent() {
        return absent;
    }

    public void setAbsent(int absent) {
        this.absent = absent;
    }

    public int getLate() {
        return late;
    }

    public void setLate(int late) {
        this.late = late;
    }

    public int getSl() {
        return sl;
    }

    public void setSl(int sl) {
        this.sl = sl;
    }

    public int getPbl() {
        return pbl;
    }

    public void setPbl(int pbl) {
        this.pbl = pbl;
    }

}


