package entities;
// Generated Jun 17, 2017 2:06:25 AM by Hibernate Tools 4.3.1



/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private String subjectId;
     private String subjectName;
     private Integer term;
     private Integer academicYear;
     private String teacherId;

    public Subject() {
    }

	
    public Subject(String subjectId) {
        this.subjectId = subjectId;
    }
    public Subject(String subjectId, String subjectName, Integer term, Integer academicYear, String teacherId) {
       this.subjectId = subjectId;
       this.subjectName = subjectName;
       this.term = term;
       this.academicYear = academicYear;
       this.teacherId = teacherId;
    }
   
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    public Integer getTerm() {
        return this.term;
    }
    
    public void setTerm(Integer term) {
        this.term = term;
    }
    public Integer getAcademicYear() {
        return this.academicYear;
    }
    
    public void setAcademicYear(Integer academicYear) {
        this.academicYear = academicYear;
    }
    public String getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }




}


